version: '3.7'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 9000:9000
    depends_on:
      - mysqldb
    volumes:
      - ./app:/root:rw,cached

  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3308:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql
